version: '3'
services:
  app:
    container_name: students
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - students_db
    env_file:
      - .env

  students_db:
    image: postgres
    container_name: students_db
    restart: always
    ports: 
      - 5544:5432
    volumes: 
      - pg:/var/lib/postgresql/data
    env_file:
      - .env
  
volumes:
  pg:
